oauth2:
  google:
    # 
    # client-id: ''
    # client-secret:'ss 
    #    redirect-uri: 'http://localhost:8083/lgoin/oauth2/code/google'
    # redirect-uri: 'http://localhost:3000'
    # token-uri: https://oauth2.googleapis.com/token
    # resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
